name: 'over_react_todo_app'
version: 0.0.1
description: Basic over_react Todo App
environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  over_react: '^1.2.0'
  w_flux: '2.6.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- over_react
- dart_to_js_script_rewriter
